### ISSUE TITLE
Invoke your service through the Salesforce CLI using a plugin

### ISSUE THREAD

**Issue by wadewegner** [benedwards44/sfcodeclean#1]
Per my [comment on Twitter](https://twitter.com/WadeWegner/status/934823184066494465), I'd like to collaborate on an extension that lets you use this service from the Salesforce CLI.

It'd be nice if you had an endpoint that accepts the `instanceUrl` and `accessToken` and then return as JSON response with the details. We can then create a plugin (happy to help you do it here on `benedwards44` if you let me contribute) that then uses the API.

I think this would help people feel better about using the service by letting them create scratch orgs, only pushing the source they are willing to have scanned into the scratch org, scan it, then delete the scratch org.

Thanks!

**Comment by benedwards44** [comment]
All up and running. Check the README for instructions, or check the instructions at https://sfcodeclean.herokuapp.com/

**Comment by SamuelSalesforce** [comment]
I get the following error when running process on my sandbox: There was an error processing your request: value too long for type character varying(120)
Can you please explain to me the issue and how can I  fix it 
Much appreciated
